// Shared simulated market data, used by the Markets page and the admin
// Copy Trading tool so both stay in sync on symbol/name/price.
export const STOCKS = [
  {
    id: "aapl",
    logoDomain: "apple.com",
    symbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    price: 227.50,
    changePercent: 1.8,
    marketCap: "$3.4T",
    volume: "52.3M",
    desc: "Designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and services. One of the most widely held stocks in the world.",
    badge: "TOP PICK",
  },
  {
    id: "nvda",
    logoDomain: "nvidia.com",
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Semiconductors",
    price: 138.20,
    changePercent: 3.2,
    marketCap: "$3.4T",
    volume: "210M",
    desc: "Leading designer of GPUs and AI computing platforms powering data centers, gaming, and autonomous systems worldwide.",
    badge: "TRENDING",
  },
  {
    id: "msft",
    logoDomain: "microsoft.com",
    symbol: "MSFT",
    name: "Microsoft Corporation",
    sector: "Technology",
    price: 445.90,
    changePercent: 0.6,
    marketCap: "$3.3T",
    volume: "18.7M",
    desc: "Global leader in software, cloud computing (Azure), and productivity platforms serving enterprises and consumers alike.",
    badge: "",
  },
  {
    id: "amzn",
    logoDomain: "amazon.com",
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    sector: "Consumer Discretionary",
    price: 218.40,
    changePercent: -0.4,
    marketCap: "$2.3T",
    volume: "34.1M",
    desc: "E-commerce and cloud computing giant, with AWS powering a significant share of the internet's infrastructure.",
    badge: "",
  },
  {
    id: "googl",
    logoDomain: "abc.xyz",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    sector: "Communication Services",
    price: 196.75,
    changePercent: 1.1,
    marketCap: "$2.4T",
    volume: "22.5M",
    desc: "Parent company of Google, with dominant positions in search, advertising, cloud, and AI research.",
    badge: "NEW",
  },
  {
    id: "vti",
    logoDomain: "vanguard.com",
    symbol: "VTI",
    name: "Vanguard Total Stock Market ETF",
    sector: "Diversified ETF",
    price: 298.10,
    changePercent: 0.3,
    marketCap: "$1.7T AUM",
    volume: "3.2M",
    desc: "Low-cost, broadly diversified fund tracking the entire U.S. stock market — a core holding for long-term investors.",
    badge: "LOW RISK",
  },
] as const;

export type Stock = typeof STOCKS[number];
